export const FETCH_SPEAKERS_START = "FETCH_SPEAKERS_START";
export const FETCH_SPEAKERS_SUCCESS = "FETCH_SPEAKERS_SUCCESS";
export const FETCH_SPEAKERS_FAIL = "FETCH_SPEAKERS_FAIL";

export const PURCHASE_PASS_START = "PURCHASE_PASS_START";
export const PURCHASE_PASS_SUCCESS = "PURCHASE_PASS_SUCCESS";
export const PURCHASE_PASS_FAIL = "PURCHASE_PASS_FAIL";
